baseURL = "https://example.com"
title = "tracks and traces"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "in progress. blog of Logan Williams/subject.space."
  copyright = "Logan Williams"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:year/:month/:day/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true